### Get All Blogs
GET http://localhost:3003/api/blogs/

### Get Blog By ID
GET http://localhost:3003/api/blogs/67d4d690b83d9c312930b99c

### Post Blog Post
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllveW9NY0dlZTIiLCJpZCI6IjY3ZDRmMjE1MWJjOWQzN2JjOGM1NjI2YiIsImlhdCI6MTc0MjAyNzE1NiwiZXhwIjoxNzQyMDMwNzU2fQ.KoJgHHXwqTaFmpJPoYo2o9tvedRBkzy3X0C8C2rkBts

{
    "title": "test1",
    "author": "test1",
    "url": "test1",
    "likes": 1
}

### Delete Blog By ID
DELETE http://localhost:3003/api/blogs/67d501f07134d39fda37daed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllveW9NY0dlZSIsImlkIjoiNjdkNGQ2OTBiODNkOWMzMTI5MzBiOTljIiwiaWF0IjoxNzQyMDIzNjMwLCJleHAiOjE3NDIwMjcyMzB9.AiSfxF70vj-y8Ma5G4TVxUkD4vQw6sBzt-PemULQQTA

### Delete Blog By ID Different User
DELETE http://localhost:3003/api/blogs/67d501f07134d39fda37daed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllveW9NY0dlZTIiLCJpZCI6IjY3ZDRmMjE1MWJjOWQzN2JjOGM1NjI2YiIsImlhdCI6MTc0MjAyNTg4NywiZXhwIjoxNzQyMDI5NDg3fQ.3QgKj5rbdUCgSSog00f-fNwNcOlbq9_wS4XkqQJ57S0


### Update Blog by ID
PUT http://localhost:3003/api/blogs/67d66c989c39482e6fdc6cc0 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI2N2Q2MGMxYTU2YTVjOGFkYTFhODcwNWYiLCJpYXQiOjE3NDIxMDY0ODAsImV4cCI6MTc0MjExMDA4MH0.hS_VsQDqEHPre-VoaJ2aDtTjF7Tn451v9jcI3zOI4qk

{
    "title": "Real Title 1",
    "author": "Real Author 1",
    "url": "http://www.helloworld.com",
    "likes": 2
}

### TESTING???
POST http://localhost:3003/api/blogs/test HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IllveW9NY0dlZSIsImlkIjoiNjdkNGQ2OTBiODNkOWMzMTI5MzBiOTljIiwiaWF0IjoxNzQyMDEyNTY2LCJleHAiOjE3NDIwMTYxNjZ9.vACMZaq549oliCZ3ZX1lGnkj70ONi3A6qYKf5eVkg6g

{
    "title": "test1",
    "author": "test1",
    "url": "test1",
    "likes": 1
}