GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/67cfdd224f31609a5c00fdf1

###
GET http://localhost:3003/info

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "test1",
    "author": "test1",
    "url": "test1",
    "likes": 1
}

###
DELETE http://localhost:3003/api/blogs/67d347da0e8b222e2fd9077c

###
PUT http://localhost:3003/api/blogs/67d35dd5e8947f22d45d2b83 HTTP/1.1
content-type: application/json

{
    "author": "Yoyo McGee",
    "url": "testPut",
    "likes": 2
}